make dist update 55ko d'archive

diff --git a/projet/Makefile b/projet/Makefile
--- a/projet/Makefile
+++ b/projet/Makefile
@@ -16,9 +16,9 @@ CFLAGS = -Wall -O3
 CPPFLAGS = -I.
 LDFLAGS = -lm -lassimp -lSDL2_image
 # définition des fichiers et dossiers
-PACKNAME = demo
+PACKNAME = API8_2024
 PROGNAME = demo
-VERSION = 1.3
+VERSION = 1.0
 distdir = $(PACKNAME)_$(PROGNAME)-$(VERSION)
 HEADERS = $(wildcard headers/*.h)
 SOURCES = main.c $(wildcard sources/*.c)
@@ -26,7 +26,7 @@ MSVCSRC = $(patsubst %,<ClCompile Include=\"%\\\" \\/>,$(SOURCES))
 OBJ = $(SOURCES:.c=.o)
 DOXYFILE = documentation/Doxyfile
 VSCFILES = $(PROGNAME).vcxproj $(PROGNAME).sln
-EXTRAFILES = COPYING $(wildcard shaders/*.?s images/*) $(VSCFILES)
+EXTRAFILES = COPYING $(wildcard shaders/*.?s models/* audio/* ) $(VSCFILES)
 DISTFILES = $(SOURCES) Makefile $(HEADERS) $(DOXYFILE) $(EXTRAFILES)
 # Traitements automatiques pour ajout de chemins et options (ne pas modifier)
 ifneq (,$(shell ls -d /usr/local/include 2>/dev/null | tail -n 1))
@@ -60,10 +60,12 @@ dist: distdir
 	$(CHMOD) -R a+r $(distdir)
 	$(TAR) zcvf $(distdir).tgz $(distdir)
 	$(RM) -r $(distdir)
+# $(MAKE) msvc # Comment out this line if not needed
 zip: distdir
 	$(CHMOD) -R a+r $(distdir)
 	$(ZIP) -r $(distdir).zip $(distdir)
 	$(RM) -r $(distdir)
+# $(MAKE) msvc # Comment out this line if not needed
 distdir: $(DISTFILES)
 	$(RM) -r $(distdir)
 	$(MKDIR) $(distdir)
@@ -75,10 +77,14 @@ doc: $(DOXYFILE)
 	mv -f $<.new $<
 	cd documentation && doxygen && cd ..
 msvc: $(VSCFILES)
-	@echo "Now these files ($?) already exist. If you wish to regenerate them, you should first delete them manually."  
+	@echo "Now these files ($?) already exist. If you wish to regenerate them, you should first delete them manually."
 $(VSCFILES):
-	@echo "Generating $@ ..."
-	@cat ../../Windows/templates/gl4dSample$(suffix $@) | sed -e "s/INSERT_PROJECT_NAME/$(PROGNAME)/g" | sed -e "s/INSERT_TARGET_NAME/$(PROGNAME)/" | sed -e "s/INSERT_SOURCE_FILES/$(MSVCSRC)/" > $@
+	@if [ -f ../../Windows/templates/gl4dSample$(suffix $@) ]; then \
+		echo "Generating $@ ..."; \
+		cat ../../Windows/templates/gl4dSample$(suffix $@) | sed -e "s/INSERT_PROJECT_NAME/$(PROGNAME)/g" | sed -e "s/INSERT_TARGET_NAME/$(PROGNAME)/" | sed -e "s/INSERT_SOURCE_FILES/$(MSVCSRC)/" > $@; \
+	else \
+		echo "Template file ../../Windows/templates/gl4dSample$(suffix $@) not found. Skipping generation of $@"; \
+	fi
 clean:
 	@$(RM) -r $(PROGNAME) $(OBJ) *~ $(distdir).tgz $(distdir).zip gmon.out	\
 	  core.* documentation/*~ shaders/*~ documentation/html
